name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build && npm run package

      - name: Generate changelog
        uses: ./
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output-file: ./docs/CHANGELOG.md

      - name: Git commit changelog
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "lib/ dist/ docs/"
          message: "chore(release): Release ${{steps.vars.outputs.VERSION}}"
          push: origin HEAD:master

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v1
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          body: ${{ steps.changelog.outputs.changelog }}
          fail_on_unmatched_files: true

      - uses: nowactions/update-majorver@v1
